### ISSUE TITLE
README sample isn't working

### ISSUE THREAD

**Issue by stevenhaddox** [rack-amqp/rack-amqp#1]
When running rabbitmq:

```
$ rabbitmq-server 

              RabbitMQ 3.2.1. Copyright (C) 2007-2013 GoPivotal, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /usr/local/var/log/rabbitmq/rabbit@localhost.log
  ######  ##        /usr/local/var/log/rabbitmq/rabbit@localhost-sasl.log
  ##########
              Starting broker... completed with 10 plugins.
```

And running the `sample_client` script against the simple.ru script:

```
$ ruby sample_client.rb 

Request Path: /
```

I receive the following error:

```
$ ruby rackable.rb simple.ru 
go go go
Received message: "/"
/Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:20:in `assert': SCRIPT_NAME must start with / (Rack::Lint::LintError)
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:246:in `check_env'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:43:in `_call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:217:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    from rackable.rb:40:in `handle_request'
    from rackable.rb:55:in `block (2 levels) in <main>'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/consumer.rb:164:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/consumer.rb:164:in `block in on_delivery'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/callbacks.rb:37:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/callbacks.rb:37:in `block in exec_callback'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/callbacks.rb:37:in `each'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/callbacks.rb:37:in `exec_callback'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/consumer.rb:299:in `handle_delivery'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/consumer.rb:345:in `block in <class:Consumer>'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/session.rb:967:in `call'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/session.rb:967:in `receive_frameset'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/session.rb:941:in `receive_frame'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp/session.rb:679:in `receive_data'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /Users/steven/.rvm/gems/ruby-2.0.0-p0/gems/amqp-1.1.5/lib/amqp.rb:56:in `start'
    from rackable.rb:50:in `<main>'
```

I know it's connecting to rabbitmq properly as it threw an error when I forgot to run it first. I installed rabbitmq via homebrew and the rest of the gems via bundler.

**Comment by jszmajda** [comment]
Interesting that the Linter blew up. I removed it in the latest commit, try it now.
